name: Deploy to Render
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker
        run: docker build -t youtube-hls-proxy .
      # You can add steps to push to Render using Render's API token
